### ISSUE TITLE
Problem when updating from v0 to v1

### ISSUE THREAD

**Issue by selsta** [eine/setup-msys2#24]
Sorry, might be an unrelated problem but I can’t figure it out currently.

When updating to v1 a simple `sed` command suddenly breaks: https://github.com/selsta/monero-gui/runs/745783813

Here is the same with v0: https://github.com/selsta/monero-gui/runs/739286405

Any idea what changed?

**Comment by eine** [comment]
Hi @selsta! On the one hand, it seems that you are missing quotes in `run: msys2 sed -i 's/CONFIG\ +=\ qtquickcompiler//' monero-wallet-gui.pro`. On the other hand, you are using `msys2` command inline, hence your args are separated according to whitespaces, which might break your sed command. I suggest to use the `defaults: run: shell:` approach (see https://github.com/eine/setup-msys2#usage). Moreover, I suggest to use option `install` and v2 of actions/checkout.

```yml
defaults:
  run:
    shell: msys2 {0}
steps:
- uses: actions/checkout@v2
  fetch-depth: 0
- uses: eine/setup-msys2@v1
  with:
    update: true
    install: mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-libusb git mingw-w64-x86_64-qt5 mingw-w64-x86_64-libgcrypt
- name: build
  run: |
    # disable qtquickcompiler
    sed -i 's/CONFIG\ +=\ qtquickcompiler//' monero-wallet-gui.pro
    ./build.sh release
- name: test qml
  run: build/release/bin/monero-wallet-gui --test-qml
```
